### ISSUE TITLE
Pre-V8s to-do list

### ISSUE THREAD

**Issue by rickselby** [rickselby/conelanders#214]
- [x] Add an option to each championship to group team championship standings by team size
- [x] Add a 'short name' to each race for the top of the drivers championship table (and other places)
- [x] Add penalty points, per race/event, showing at event level and overall 
  - if possible, give reason, and show reason in tooltip on results pages

**Comment by rickselby** [comment]
#218
